[package]
name = "slarti-hosts"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
slarti-sshcfg = { path = "../slarti-sshcfg" }
dirs-next = { workspace = true }
serde = { workspace = true, features = ["derive"] }
